### ISSUE TITLE
Başı [DM] olan cezalandırmalar için

### ISSUE THREAD

**Issue by thefurkanozkan** [CanTheCoderBoi/Excalibur-Geri-Bildirim#4]
Eğer ki bir ban/kick/warn/tempban ın sebebinin ilk kelimesi [DM] ise o kullanıcı özelden bilgilendirilecek

**Comment by CanTheCoderBoi** [comment]
Ben hallederim

**Comment by CanTheCoderBoi** [comment]
Üstünde çalışmaya başladım.
