### ISSUE TITLE
Temizle komutunda komutu kullanamayacağımızı bildiren bir mesaj belirtsin

### ISSUE THREAD

**Issue by barbarabr3388** [CanTheCoderBoi/Excalibur-Geri-Bildirim#6]
##Discord Tag ve ID'niz:
SADECE BARIŞ!#4881 | 331846231514939392

##İstediğiniz özelliği açıklayınız:
Temizle komutundan sonra ":lock: Bu komutu gerçekleştirmek için gereken yetkiye sahip değilsiniz." uyarısını verebilir

**Comment by CanTheCoderBoi** [comment]
Bunun nedeni, temizle komutuna aslında "temizle" önekini eklemeyi unutmuş olmamız. Onu da #7 düzelteceğimi söyledim.
