### ISSUE TITLE
[BUG] temizle çalışmıyor!

### ISSUE THREAD

**Issue by barbarabr3388** [CanTheCoderBoi/Excalibur-Geri-Bildirim#7]
**SunucuID:**
403879632656662528
##**Hatayı Açıklayın**
.t .purge vb çalışmakta ancak asıl komut olan temizle çalışmamakta (purge veriyor temizle yetkisizlerde uyarı vermiyor)

##**Hatayı Elde Etmek İçin Yapmamız Gerenler**
1. Şu komutu çalıştır => temizle (yetkisiz)
2. Şunu değiştir => komutu => purge (yetkisiz)
4. Hatayı gör => cevap yok

##**Olması Gereken Şey**
normalde ":lock: Bu komutu gerçekleştirmek için gereken yetkiye sahip değilsiniz." olarak cevap vermeli

##**Ekran Görüntüleri**
Mümkünse ekran görüntüleriyle de hatanın yapılışını, hata sonucunu gösterebilirsiniz.

**Comment by CanTheCoderBoi** [comment]
Hemen Düzeltiyorum teşekkürler.
