### ISSUE TITLE
[BUG] bilgi komutunda hata var

### ISSUE THREAD

**Issue by barbarabr3388** [CanTheCoderBoi/Excalibur-Geri-Bildirim#8]
**SunucuID:**
403879632656662528
##**Hatayı Açıklayın**
.bilgi yazınca yardım komutunu atıyor ama .info komutunda da var bilgi aliası

##**Hatayı Elde Etmek İçin Yapmamız Gerenler**
1. Şu komutu çalıştır => .info
2. Şunu değiştir => komut => .bilgi
4. Hatayı gör => bilgi info aliası olmasına rağmen yardım komutu geliyor

##**Olması Gereken Şey**
info komutu gelmeli

##**Ekran Görüntüleri**
Mümkünse ekran görüntüleriyle de hatanın yapılışını, hata sonucunu gösterebilirsiniz.

**Comment by CanTheCoderBoi** [comment]
Güzel Güzel Güzel Düzeltiyorum
